### ISSUE TITLE
Some issues with the addon currently in Wrath Classic

### ISSUE THREAD

**Issue by Hills505** [ZelionGG/XIV_Databar-Continued#1]
![Currency](https://user-images.githubusercontent.com/126447904/221494770-e6725df2-13c7-4482-822a-3091cdb5e73e.png)
![Gold](https://user-images.githubusercontent.com/126447904/221494774-7db1ae62-2307-4a33-b121-03a37922b7e7.png)
![System](https://user-images.githubusercontent.com/126447904/221494775-a158f7aa-0faf-4c76-b8fe-86c4a9c317ee.png)
![Tradeskills](https://user-images.githubusercontent.com/126447904/221494777-052fdc8e-7b79-476e-b232-866d34180f0d.png)

The above are screenshots of the issues. I have tried with the bar both full screen and centered for the options. My main issues have been that whenever I have the modules currency, gold, and tradeskills enabled, they do not display anything on the bar. When gold is enabled it makes the System module bug out and disappear. 

Bugsack had no errors caught in it with these settings enabled, sorry for the lack of info otherwise. If there is anything I should try please post me

Thanks for keeping this going

**Comment by Hills505** [comment]
not sure if this helps at all to fixing it. Finally got an error in bugsack. no idea if it is related to any of the above issues.

40x ...eXIV_Databar_Continued/modules/micromenu.lua:628: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@XIV_Databar_Continued/modules/micromenu.lua"]:628: in function <...eXIV_Databar_Continued/modules/micromenu.lua:507>

Locals:
(*temporary) = "%s %s %s"
(*temporary) = "(|cffecd672Gaya-No Info|r)"
(*temporary) = nil
(*temporary) = "|A:UI-ChatIcon-App:16:16:0:0|a"
(*temporary) = "string expected, got nil"

**Comment by ZelionGG** [comment]
Thank you for this.

I just released the v2.0 of the addon that should make the addon work as expected on Classic. I invite you to try out the new version and tell me if everything is working for you.
