### ISSUE TITLE
Bug in version 2.6

### ISSUE THREAD

**Issue by PziCrow** [ZelionGG/XIV_Databar-Continued#11]
Version 2.6 causes a continuous bug, making it nearly impossible to copy the lua string. But here's what I managed to copy.

2245x XIV_Databar_Continued/Core/modules/system.lua:38: attempt to index field 'system' (a nil value)
[string "@XIV_Databar_Continued/Core/modules/system.lua"]:38: in function `Refresh'
[string "@XIV_Databar_Continued/Core/modules/system.lua"]:25: in function <XIV_Databar_Continued/Cor

Version 2.5 works fine.

**Comment by ZelionGG** [comment]
Heya, thank you for the feedback, as I said in issue #8, a fix will come very soon.

**Comment by ZelionGG** [comment]
Version 2.6.1 is now released and should fix bugs introduced in version 2.6. 

Let me know if you encounter any bugs and thanks again for the feedback !

**Comment by PziCrow** [comment]
Bugfree. Thanks a lot :D

**Comment by ZelionGG** [comment]
Sweet, thanks again for the feedback and enjoy !
