### ISSUE TITLE
[Bug] Currency module doesn't work after v2.3.1 on vanilla/wotlk clients.

### ISSUE THREAD

**Issue by Amanthuul** [ZelionGG/XIV_Databar-Continued#15]
**Describe the bug**
Currency module doesn't work after v2.3.1 on vanilla/wotlk clients.

**To Reproduce**
Enable currency module, enable show xp, enable currency tracking, frames don't show up.

**Expected behavior**
Curency shows up if tracking enabled. XP bar shows up until char is max lvl.

**Lua error logs**
None

**Screenshots**
<img width="495" alt="image" src="https://github.com/ZelionGG/XIV_Databar-Continued/assets/18071324/696b7226-b9dc-4ce5-b918-506ff117bd33">

**WoW Version (please complete the following information)**
 - Classic Wrath, Vanilla Classic

**XIV_Databar Continued Version**
 Everything after 2.3.1

**Comment by Amanthuul** [comment]
Found it!

It's basically this commit https://github.com/ZelionGG/XIV_Databar-Continued/commit/6856f0b12a455541a9c20465934b2b726b2054d0

This got deleted 
`local anchorFrame = xb:GetFrame('tradeskillFrame')`

**Comment by ZelionGG** [comment]
Heya, thanks for the report ! 

I'll investigate that tonight and will keep you updated.

**Comment by ZelionGG** [comment]
Heya, 2.7 should fix your issue with the module ! 

Let me know if you still have issues and thank you again for the feedback.
