### ISSUE TITLE
Error in the "Load_Changelog.xml" file

### ISSUE THREAD

**Issue by Burschle24** [ZelionGG/XIV_Databar-Continued#22]
The entry of the old and new 2.7.x file is missing...

	<Script file='Old/v2/2.7.1.lua'/>
	<Script file='Old/v2/2.7.2.lua'/>
	
	<Script file='2.7.3.lua'/>

**Comment by ZelionGG** [comment]
Heya, thank you for the feedback.

I just checked and you're right, sorry for that, I pushed the version while I was in the middle of a pretty bad illness so I wasn't 100% focused, I'll push a fixed version today.

**Comment by Burschle24** [comment]
no problem, i hope you are well again by now :)

**Comment by ZelionGG** [comment]
Doing way better thank you !

New release 2.7.3-fix1 should fix the Changelog issues !

Thank you again for helping me make XIV Databar better 😄
