### ISSUE TITLE
Font issue [Bug] 

### ISSUE THREAD

**Issue by buddy75** [ZelionGG/XIV_Databar-Continued#24]
**Describe the bug**
Went Looting a mob that drops a green item 

**To Reproduce**

**Expected behavior**

**Lua error logs**
A copy-paste of your Lua errors.

**Screenshots**

**WoW Version (please complete the following information)**
 - WoW Flavour:  Cata Classic 4.4
 - Version

**XIV_Databar Continued Version**
Which version of XIV_Databar Continued are you using ? 2.8

**Additional context**
Message: FontString:SetText(): Font not set
Lua Taint: XIV_Databar_Continued
Time: Fri May 17 19:08:45 2024
Count: 6
Stack: FontString:SetText(): Font not set
Lua Taint: XIV_Databar_Continued
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetText'
[string "@Interface/AddOns/XIV_Databar_Continued/Classic/modules/Wrath/travel.lua"]:388: in function `?'
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BagSync/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ce/AddOns/BagSync/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Im not sure if its your Beautiful addon or All the Things so i figure i would post here if not ill post in their discord

**Comment by ZelionGG** [comment]
Heya, can you try disabling AllTheThings and check if the error persists please ?

**Comment by Blazeflack** [comment]
I experience the same type of bug on Classic Era.

```
17x FontString:SetText(): Font not set
Lua Taint: XIV_Databar_Continued
[string "=[C]"]: in function `SetText'
[string "@XIV_Databar_Continued/Classic/modules/Vanilla/travel.lua"]:377: in function `?'
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@BagBrother/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = FontString {
}
(*temporary) = nil
```

It seems to happen on various events. I had the error appear when I gained a level, and I also get it when I use a potion during combat. When using the potion I simply clicked the action slot, using default Action Bars from WoW.

**Comment by ZelionGG** [comment]
Heya, release 3.3 should at last fix that issue ! Let me know if you still encounter any bug !
