### ISSUE TITLE
Issue in DF - Latest patch 

### ISSUE THREAD

**Issue by Purpdrankstyle** [ZelionGG/XIV_Databar-Continued#3]
Hiya,

Having the following issues - Dragonflight latest patch.

280x .../XIV_Databar_Continued/Mainline/modules/currency.lua:127: attempt to index local 'anchorFrame' (a nil value)
[string "@XIV_Databar_Continued/Mainline/modules/currency.lua"]:127: in function `Refresh'
[string "@XIV_Databar_Continued/Mainline/modules/currency.lua"]:41: in function <.../XIV_Databar_Continued/Mainline/modules/currency.lua:32>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:751: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Issue 2 

140x AceLocale-3.0-6: XIV_Databar_Continued: Missing entry for 'Set Loadout'
[string "@XIV_Databar_Continued/Mainline/modules/talent.lua"]:453: in function `CreateLoadoutPopup'
[string "@XIV_Databar_Continued/Mainline/modules/talent.lua"]:219: in function `Refresh'
[string "@XIV_Databar_Continued/Mainline/modules/talent.lua"]:98: in function <...ns/XIV_Databar_Continued/Mainline/modules/talent.lua:77>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:751: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Issue 3

140x XIV_Databar_Continued/Mainline/modules/load_modules.xml:4 Error loading XIV_Databar_Continued/clock.lua

Issue 4

140x Interface\FrameXML\Bindings.xml:1 XIV_Databar_Continued/Mainline/modules/load_modules.xml:4 Error loading XIV_Databar_Continued/clock.lua

Any ideas would be great as I love this addon :)

**Comment by ZelionGG** [comment]
Hi,

Are these errors fatal errors (addon not working) or just LUA warnings that you see in your game ?

**Comment by Purpdrankstyle** [comment]
These are just LUA errors - addon is showing and working but these errors are the only ones showing up now.

**Comment by ZelionGG** [comment]
Hi @Purpdrankstyle, do you still have those issues ? Thank you and sorry for the wait.

**Comment by ZelionGG** [comment]
Closed because of inactivity.
