### ISSUE TITLE
[Bug] Vanilla guild button goes to Raid window

### ISSUE THREAD

**Issue by Amanthuul** [ZelionGG/XIV_Databar-Continued#31]
**Describe the bug**
Vanilla guild button goes to Raid window

**WoW Version (please complete the following information)**
 - WoW Flavour: Classic
 - Version: 1.15.3

**XIV_Databar Continued Version**
3.0

**Additional context**
Vanilla now has modern guild UI, so Guild button needs to show it instead of social tab.

**Comment by ZelionGG** [comment]
Heya, version 3.0.1 should fix that issue.

Thank you again for the feedback ! 

Have a great one.

**Comment by Amanthuul** [comment]
Thanks, everything's ok now.

**Comment by ZelionGG** [comment]
Sweet thank you!
