### ISSUE TITLE
[Bug] MicroMenu doesnt work

### ISSUE THREAD

**Issue by Silvereyes1372** [ZelionGG/XIV_Databar-Continued#32]
**Describe the bug**
If I click on the talent button I have this error : 

```
8x ...XIV_Databar_Continued/Mainline/modules/micromenu.lua:969: attempt to call global 'ToggleTalentFrame' (a nil value)
[string "@XIV_Databar_Continued/Mainline/modules/micromenu.lua"]:969: in function <...XIV_Databar_Continued/Mainline/modules/micromenu.lua:964>

Locals:
self = talent {
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = "attempt to call global 'ToggleTalentFrame' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 fontFlags = <table> {
 }
 defaultModuleState = true
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 enabledState = true
 Changelog = <table> {
 }
 name = "XIV_Databar_Continued"
 orderedModules = <table> {
 }
 LSM = <table> {
 }
 constants = <table> {
 }
 timerRefresh = true
 defaultModuleLibraries = <table> {
 }
 L = <table> {
 }
}
```

And If I click on the spellbook button I've got this one : 

```
11x ...ParentPanelManager/Mainline/UIParentPanelManager.lua:831: attempt to index local 'frame' (a nil value)
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:831: in function `ToggleFrame'
[string "@XIV_Databar_Continued/Mainline/modules/micromenu.lua"]:960: in function <...XIV_Databar_Continued/Mainline/modules/micromenu.lua:955>

Locals:
frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"


```

Version 3.0

**Comment by ZelionGG** [comment]
Hi, thank you for the feedback, I'll update the addon soon !

**Comment by Silvereyes1372** [comment]
Thank you for your work! <3

**Comment by ZelionGG** [comment]
Heya, version 3.0.1 should fix the micromenu issues, let me know if you have any issue !

Thank you again for the feedback ! 

Have a great one.

**Comment by Silvereyes1372** [comment]
It works perfectly ty , got another error tho for should I make another post ?

7x .../XIV_Databar_Continued/Mainline/modules/currency.lua:76: attempt to compare number with nil
[string "@XIV_Databar_Continued/Mainline/modules/currency.lua"]:76: in function `Refresh'
[string "@XIV_Databar_Continued/Mainline/modules/currency.lua"]:41: in function <.../XIV_Databar_Continued/Mainline/modules/currency.lua:32>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 curText = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 xpBarBg = Texture {
 }
 xpText = FontString {
 }
 xpIcon = Texture {
 }
 xpFrame = Button {
 }
 currencyFrame = Frame {
 }
 curIcons = <table> {
 }
 curButtons = <table> {
 }
 intToOpt = <table> {
 }
 name = "XIV_Databar_Continued_CurrencyModule"
 orderedModules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 xpBar = StatusBar {
 }
 hooks = <table> {
 }
 enabledState = true
 rerollItems = <table> {
 }
 defaultModuleState = true
 moduleName = "CurrencyModule"
}
db = <table> {
 modules = <table> {
 }
 selectedHearthstones = <table> {
 }
 general = <table> {
 }
 color = <table> {
 }
 text = <table> {
 }
 hearthstonesList = <table> {
 }
 dalaran_hs_string = "Pierre de foyer de Dalaran"
}
iconSize = 15
(*temporary) = 70
(*temporary) = nil
(*temporary) = 3
(*temporary) = Button {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
xb = <table> {
 defaults = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 fontFlags = <table> {
 }
 defaultModuleState = true
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 enabledState = true
 Changelog = <table> {
 }
 name = "XIV_Databar_Continued"
 orderedModules = <table> {
 }
 LSM = <table> {
 }
 constants = <table> {
 }
 timerRefresh = false
 defaultModuleLibraries = <table> {
 }
 L = <table> {
 }
}


I think it's realated to MAX_PLAYER_LEVEL returning nil but i dont know anything about lua code so ¯\_(ツ)_/¯

But if I Set  MAX_PLAYER_LEVEL to 80 it works (or 70 for prepatch)

**Comment by ZelionGG** [comment]
Heya, yeah transfer this request in another issue please for a better tracking. I'll investigate that thank you again !
