### ISSUE TITLE
[Bug] Numerous Bugs

### ISSUE THREAD

**Issue by amw83** [ZelionGG/XIV_Databar-Continued#36]
When you mouse over the Dalaran Hearthstone you instantly get an error

**To Reproduce**
1. Move your mouse of the Dalaran Hearthstone option in the bottom right hand corner.
2

Message: ...ns/XIV_Databar_Continued/Mainline/modules/travel.lua:645: attempt to call global 'GetSpellCooldown' (a nil value)
Time: Sun Aug 18 15:53:24 2024
Count: 5
Stack: ...ns/XIV_Databar_Continued/Mainline/modules/travel.lua:645: attempt to call global 'GetSpellCooldown' (a nil value)
[string "@Interface/AddOns/XIV_Databar_Continued/Mainline/modules/travel.lua"]:645: in function `ShowTooltip'
[string "@Interface/AddOns/XIV_Databar_Continued/Mainline/modules/travel.lua"]:209: in function <...ns/XIV_Databar_Continued/Mainline/modules/travel.lua:206>

Locals: self = <table> {
 hearthFrame = TravelModule {
 }
 portButtons = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 defaultModuleState = true
 selectedHearthstones = <table> {
 }
 extraPadding = 30
 enabledState = true
 hearthButton = hearthButton {
 }
 garrisonHearth = 110560
 useElvUI = true
 defaultModuleLibraries = <table> {
 }
 portOptions = <table> {
 }
 iconPath = "Interface\AddOns\XIV_Databar_Continued\media\datatexts\repair"
 orderedModules = <table> {
 }
 portOptionString = FontString {
 }
 portPopup = portPopup {
 }
 portText = FontString {
 }
 portIcon = Texture {
 }
 hearthText = FontString {
 }
 hearthIcon = Texture {
 }
 optionTextExtra = 4
 availableHearthstones = <table> {
 }
 name = "XIV_Databar_Continued_TravelModule"
 portButton = portButton {
 }
 moduleName = "TravelModule"
 hearthstones = <table> {
 }
}
r = 1
g = 0.486275
b = 0.039216
_ = nil
(for state) = <table> {
 193753 = <table> {
 }
 110560 = <table> {
 }
 140192 = <table> {
 }
}
(for control) = 193753
i = 193753
v = <table> {
 text = "The Dreamgrove"
 portId = 193753
}
(*temporary) = nil
(*temporary) = 193753
(*temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 fontFlags = <table> {
 }
 defaultModuleState = true
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 enabledState = true
 Changelog = <table> {
 }
 name = "XIV_Databar_Continued"
 orderedModules = <table> {
 }
 LSM = <table> {
 }
 constants = <table> {
 }
 timerRefresh = true
 defaultModuleLibraries = <table> {
 }
 L = <table> {
 }
}
L = <table> {
 Show XP Bar Below Max Level = "Show XP Bar Below Max Level"
 Right = "Right"
 Second Currency = "Second Currency"
 Cleaned = "Cleaned"
 Currency Select = "Currency Select"
 Enable Loadout Switcher = "Enable Loadout Switcher"
 Left-Click = "Left-Click"
 Bottom = "Bottom"
 Whisper BNet = "Whisper BNet"
 Show Pets Button = "Show Pets Button"
 Use Server Time = "Use Server Time"
 Hide Event Text = "Hide Event Text"
 Addons to Show in Tooltip = "Addons to Show in Tooltip"
 Open Artifact = "Open Artifact"
 Hide order hall bar = "Hide order hall bar"
 Hide BNet App Friends = "Hide BNet App Friends"
 Show Character Button = "Show Character Button"
 Local Time = "Local Time"
 Master Volume = "Master Volume"
 Whisper Character = "Whisper Character"
 Ready = "Ready"
 Hide Bar in combat = "Hide Bar in combat"
 Durability Warning Threshold = "Durability Warning Threshold"
 Use Class Colors for XP Bar = "Use Class Colors for XP Bar"
 Bar Position = "Bar Position"
 Use Class Color for Text = "Use Class Color for Text"
 Module Spacing = "Module Spacing"
 Show Chat Button = "Show Chat Button"
 Empty Hearthstones List = "If you see an empty list, /reload your UI a few seconds after the initial loading (Blizzard is loading items informations asynchronously so that's the only solution for now)."
 Modifier for friend invite = "Modifier for friend invite"
 Changelog = "Changelog"
 Bar Color = "Bar Color"
 Icon Spacing = "Icon Spacing"
 %month%-%day%-%year% = "%month%-%day%-%year%"
 Port Options = "Port Options"
 Social Text Offset = "Social Text Offset"
 Hover = "Hover"
 Current Specialization = "Current Specialization"
 Toggle Profession Spellbook = "Toggle Profession Spellbook"
 Travel = "Travel"
 Show Talents Button = "Show Talents Button"
 Colors =
**XIV_Databar Continued Version**
Current

**Screenshots**

**WoW Version (please complete the following information)**
 - WoW Flavour: [e.g Retail, Classic Wrath, Classic]: Retail
 - Version: Current

**XIV_Databar Continued Version**
Which version of XIV_Databar Continued are you using ?
Current

**Additional context**

**Comment by amw83** [comment]
Sorry, was going to both both errors in the 1 report but forgot, have logged a second ticket with the second issue (can't seem to update the Title.

**Comment by ZelionGG** [comment]
A fix have been pushed, I'll be releasing a new version tonight !
