### ISSUE TITLE
[Bug] Chat Icon throws a LUA error

### ISSUE THREAD

**Issue by amw83** [ZelionGG/XIV_Databar-Continued#37]
**Describe the bug**
When you attempt to click the chat bubble icon you get thrown a LUA error, and nothing happens.

**To Reproduce**
1. Click on the Chat Bubble Icon in the bottom left hand corner.

**Expected behavior**
TBH, I have no idea

**Lua error logs**
Message: ...ns/XIV_Databar_Continued/Mainline/modules/travel.lua:645: attempt to call global 'GetSpellCooldown' (a nil value)
Time: Sun Aug 18 15:55:15 2024
Count: 7
Stack: ...ns/XIV_Databar_Continued/Mainline/modules/travel.lua:645: attempt to call global 'GetSpellCooldown' (a nil value)
[string "@Interface/AddOns/XIV_Databar_Continued/Mainline/modules/travel.lua"]:645: in function `ShowTooltip'
[string "@Interface/AddOns/XIV_Databar_Continued/Mainline/modules/travel.lua"]:209: in function <...ns/XIV_Databar_Continued/Mainline/modules/travel.lua:206>

Locals: self = <table> {
 hearthFrame = TravelModule {
 }
 portButtons = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 defaultModuleState = true
 selectedHearthstones = <table> {
 }
 extraPadding = 30
 enabledState = true
 hearthButton = hearthButton {
 }
 garrisonHearth = 110560
 useElvUI = true
 defaultModuleLibraries = <table> {
 }
 portOptions = <table> {
 }
 iconPath = "Interface\AddOns\XIV_Databar_Continued\media\datatexts\repair"
 orderedModules = <table> {
 }
 portOptionString = FontString {
 }
 portPopup = portPopup {
 }
 portText = FontString {
 }
 portIcon = Texture {
 }
 hearthText = FontString {
 }
 hearthIcon = Texture {
 }
 optionTextExtra = 4
 availableHearthstones = <table> {
 }
 name = "XIV_Databar_Continued_TravelModule"
 portButton = portButton {
 }
 moduleName = "TravelModule"
 hearthstones = <table> {
 }
}
r = 1
g = 0.486275
b = 0.039216
_ = nil
(for state) = <table> {
 193753 = <table> {
 }
 110560 = <table> {
 }
 140192 = <table> {
 }
}
(for control) = 193753
i = 193753
v = <table> {
 text = "The Dreamgrove"
 portId = 193753
}
(*temporary) = nil
(*temporary) = 193753
(*temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
xb = <table> {
 defaults = <table> {
 }
 modules = <table> {
 }
 baseName = "XIV_Databar_Continued"
 fontFlags = <table> {
 }
 defaultModuleState = true
 frames = <table> {
 }
 miniTextPosition = "TOP"
 db = <table> {
 }
 enabledState = true
 Changelog = <table> {
 }
 name = "XIV_Databar_Continued"
 orderedModules = <table> {
 }
 LSM = <table> {
 }
 constants = <table> {
 }
 timerRefresh = true
 defaultModuleLibraries = <table> {
 }
 L = <table> {
 }
}
L = <table> {
 Show XP Bar Below Max Level = "Show XP Bar Below Max Level"
 Right = "Right"
 Second Currency = "Second Currency"
 Cleaned = "Cleaned"
 Currency Select = "Currency Select"
 Enable Loadout Switcher = "Enable Loadout Switcher"
 Left-Click = "Left-Click"
 Bottom = "Bottom"
 Whisper BNet = "Whisper BNet"
 Show Pets Button = "Show Pets Button"
 Use Server Time = "Use Server Time"
 Hide Event Text = "Hide Event Text"
 Addons to Show in Tooltip = "Addons to Show in Tooltip"
 Open Artifact = "Open Artifact"
 Hide order hall bar = "Hide order hall bar"
 Hide BNet App Friends = "Hide BNet App Friends"
 Show Character Button = "Show Character Button"
 Local Time = "Local Time"
 Master Volume = "Master Volume"
 Whisper Character = "Whisper Character"
 Ready = "Ready"
 Hide Bar in combat = "Hide Bar in combat"
 Durability Warning Threshold = "Durability Warning Threshold"
 Use Class Colors for XP Bar = "Use Class Colors for XP Bar"
 Bar Position = "Bar Position"
 Use Class Color for Text = "Use Class Color for Text"
 Module Spacing = "Module Spacing"
 Show Chat Button = "Show Chat Button"
 Empty Hearthstones List = "If you see an empty list, /reload your UI a few seconds after the initial loading (Blizzard is loading items informations asynchronously so that's the only solution for now)."
 Modifier for friend invite = "Modifier for friend invite"
 Changelog = "Changelog"
 Bar Color = "Bar Color"
 Icon Spacing = "Icon Spacing"
 %month%-%day%-%year% = "%month%-%day%-%year%"
 Port Options = "Port Options"
 Social Text Offset = "Social Text Offset"
 Hover = "Hover"
 Current Specialization = "Current Specialization"
 Toggle Profession Spellbook = "Toggle Profession Spellbook"
 Travel = "Travel"
 Show Talents Button = "Show Talents Button"
 Colors =

**Screenshots**

**WoW Version (please complete the following information)**
 - WoW Flavour: [e.g Retail, Classic Wrath, Classic]: Retail
 - Version: Current

**XIV_Databar Continued Version**
Which version of XIV_Databar Continued are you using ?
Current

**Additional context**

**Comment by ZelionGG** [comment]
Heya, thank you for the report, I was on vacation for the last 3 weeks ! I'll investigate these issues today.

**Comment by ZelionGG** [comment]
I'm really wondering if that button is of any use to someone. I feel like ppl are typing in chat to select the channel they want to use else they use the in-game button / ElvUI chat button.... Taking any feedbacks if some ppl use that little button on XIV

**Comment by amw83** [comment]
> I'm really wondering if that button is of any use to someone. I feel like ppl are typing in chat to select the channel they want to use else they use the in-game button / ElvUI chat button.... Taking any feedbacks if some ppl use that little button on XIV

To be honest, I have no idea what it's even supposed to do :D ... New to tha addon, and just noticed the issue, and since it errors and doesn't work, I had no idea what it was even intended for ... haha, did it just hide the chat window?

**Comment by ZelionGG** [comment]
> > I'm really wondering if that button is of any use to someone. I feel like ppl are typing in chat to select the channel they want to use else they use the in-game button / ElvUI chat button.... Taking any feedbacks if some ppl use that little button on XIV
> 
> To be honest, I have no idea what it's even supposed to do :D ... New to tha addon, and just noticed the issue, and since it errors and doesn't work, I had no idea what it was even intended for ... haha, did it just hide the chat window?

The goal of this button is to allow you to change the chat channel rapidly just like when you click the standard "bubble" on the left of the default Blizzard Chat, but I really doubt that this button is really used by anyone...
![image](https://github.com/user-attachments/assets/b95c8c06-582a-4f90-a80a-b7ec2eb0d8b2)

**Comment by ZelionGG** [comment]
Heya, chat icon shouldn't throw errors anymore with v3.0.3, let me know if that's the case ! 

Thank you again.
