### ISSUE TITLE
[Enhancement] Add M+ Portals to [Travel] module

### ISSUE THREAD

**Issue by ZelionGG** [ZelionGG/XIV_Databar-Continued#38]
Idea submitted by [oakensoul](https://legacy.curseforge.com/wow/addons/xiv_databar-continued?comment=29), the idea is to add an "M+ Portal" option to the travel module next to the Dalaran / Garrison HS.

This could be a clickable title with a dropdown menu.

**Comment by ZelionGG** [comment]
Hi guys, just a picture of the WIP of that new feature !

![image](https://github.com/user-attachments/assets/a1252e69-15d2-4181-b730-f3eeb91ea31d)

**Comment by ZelionGG** [comment]
Hey guys, everything is now working as expected and I'll release that new feature very soon !
I just need to do some more visual adjustments to the menu.

![image](https://github.com/user-attachments/assets/01e79dfc-137d-4c82-8b99-26dffe6e48f7)

**Comment by ZelionGG** [comment]
New iteration with some visual adjustments and a new "Current season" section !

![image](https://github.com/user-attachments/assets/d404c4b7-4678-4625-b4e5-aef173ad1a54)

**Comment by Smokenoaken** [comment]
Very glad to see this being added. Cant wait to see it implemented on the release version of XIV :)

**Comment by ZelionGG** [comment]
Heya, after such a long wait, version 3.1 is out and with it, the new Mythic+ Portals option.

Remember that this option can be enabled and disabled in the [Travel] module config.

Thank you again for the suggestion and for helping me maintain XIV Databar Continued and enjoy !
