### ISSUE TITLE
[Bug] system information and gold information overlap

### ISSUE THREAD

**Issue by ifish2007** [ZelionGG/XIV_Databar-Continued#40]
First, thank you for creating this addon. It’s both beautiful and useful.

**Describe the bug**
The system information and gold information overlap in the Traditional Chinese interface.

**Expected behavior**
The information should be separated and not overlap. The "World Ping: 140ms" and the "Gold" sections overlap.

**Lua error logs**
N/A

**Screenshots**
![image](https://github.com/user-attachments/assets/84e9e0c7-3966-4252-9e95-9401a29f7ee4)

**WoW Version (please complete the following information)**
 - WoW Flavour: [e.g Retail] 
 - Version: 11.0.2.56313

**XIV_Databar Continued Version**
3.0.3

**Additional context**
I’m wondering if the issue was caused by the Chinese font. If so, would it be easier to resolve by providing an option to change the font or language of this addon to English?

**Comment by ZelionGG** [comment]
Heya, thank you for the report, I'm currently investigating on this and will keep you updated !

**Comment by byezero** [comment]
你可以试试把汉化文件里的 每秒帧数 改为FPS 本地改为L 世界改为W 毫秒改为ms 我觉得这些用英文也是可以的。

**Comment by ifish2007** [comment]
> 你可以试试把汉化文件里的 每秒帧数 改为FPS 本地改为L 世界改为W 毫秒改为ms 我觉得这些用英文也是可以的。

不好意思，我可以請問漢化文件在哪裡嗎？

**Comment by byezero** [comment]
> > 你可以试试把汉化文件里的 每秒帧数 改为FPS 本地改为L 世界改为W 毫秒改为ms 我觉得这些用英文也是可以的。
> 
> 不好意思，我可以請問漢化文件在哪裡嗎？

[XIV_Databar-Continued](https://github.com/ZelionGG/XIV_Databar-Continued/tree/main)/[locales](https://github.com/ZelionGG/XIV_Databar-Continued/tree/main/locales)
/zhCN.lua

**Comment by ZelionGG** [comment]
Hi guys, if there's any change I need to make in the code to fix the issue, let me know and I'll do it 😉

**Comment by ZelionGG** [comment]
Closing this since there are no more comments.
