### ISSUE TITLE
[Enhancement] Combine gold tracker for horde and alliance and give option to ignore realm

### ISSUE THREAD

**Issue by kaethr01** [ZelionGG/XIV_Databar-Continued#49]
**Is your feature request related to a problem? Please describe.**
Now that Warbands are a thing and gold is freely sent between any character on your account, it would be great to see in the gold micro menu all of your characters and not have the totals split out between alliance and horde or the realm the character is on.  This could potentially be a configuration if the current behavior is still desired.

**Describe the solution you'd like**
The gold currency micro menu will show all characters on my account gold value in a single place and the total will sum them all instead of being split by faction and realm.

**Describe alternatives you've considered**
I attempted to edit the lua locally to just always treat my characters as horde and it seems to work somewhat but feels like a hacky workaround and also seems to have unforseen consequences.  My 'daily gold' number always seems to be incorrect now and often when I login it will show a very negative number without me spending anything.

I replaced all instances of `UnitFactionGroup("player")` with `"Horde"`

**Additional context**
None

**Comment by ZelionGG** [comment]
Heya, that's an interesting feedback and I'll deffo think about this enhancement !

**Comment by ZelionGG** [comment]
Heya, release 3.3 should implement listing of golds being realm and faction-agnostic, a new option is available in the Gold module part to allow you to show only the current server ! 

Hope this will fit your needs !

**Comment by kaethr01** [comment]
Fantastic, thank you!
