### ISSUE TITLE
Talents LUA error

### ISSUE THREAD

**Issue by srtzero** [ZelionGG/XIV_Databar-Continued#5]
Every time I try to enable the talents module I receive the following error:

1x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "PLAYER_SPECIALIZATION_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:137: in function `RegisterEvent'
[string "@XIV_Databar_Continued/Classic/modules/talents.lua"]:209: in function `RegisterFrameEvents'
[string "@XIV_Databar_Continued/Classic/modules/talents.lua"]:89: in function <...ns/XIV_Databar_Continued/Classic/modules/talents.lua:72>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Skillet-Classic/Skillet.lua"]:151: in function `DisableBlizzardFrame'
[string "@Skillet-Classic/Skillet.lua"]:789: in function <Skillet-Classic/Skillet.lua:670>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by ZelionGG** [comment]
Hi, seeing the lua error I guess you're on Classic WoW, am I right ?

**Comment by srtzero** [comment]
Yes.

**Comment by ZelionGG** [comment]
Talent module has been reworked in the new v2.1.2 release, this release should fix the LUA error with the talents module and should bring back the Spec Switcher.

Let me know if you have any issues with that new update.

**Comment by srtzero** [comment]
New Lua errors After updating to new v2.1.2. Separated by dashed lines.

2x ...ns/XIV_Databar_Continued/Classic/modules/talents.lua:9: Cannot find a library instance of "LibClassicInspector".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@XIV_Databar_Continued/Classic/modules/talents.lua"]:9: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibClassicInspector"."

----------------------------------------------------------------------------------------------------------------------------------------

1x ...sic/Libs/LibClassicInspector/LibClassicInspector.lua:22: LibClassicInspector requires LibDetours-1.0
[string "=[C]"]: in function `assert'
[string "@XIV_Databar_Continued/Classic/Libs/LibClassicInspector/LibClassicInspector.lua"]:22: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "LibClassicInspector requires LibDetours-1.0"

-----------------------------------------------------------------------------------------------------------------------------------------

1x XIV_Databar_Continued/Classic/Libs/LibClassicInspector/LibClassicInspector.lua:1 (null)

-----------------------------------------------------------------------------------------------------------------------------------------

1x Interface_Wrath\FrameXML\Bindings.xml:1 XIV_Databar_Continued/Classic/modules/talents.lua:1 (null)

**Comment by ZelionGG** [comment]
Hi, sorry for that, LibDetours wasn't embedded in XIV and I had it embeded in another addon so I didn't have this error.
New version 2.2.1 should now embed this library and you should no longer have any LUA errors with the talents module.

Let me know if you still have LUA errors or if that version fixed everything.

Thank you again for the reports.

**Comment by srtzero** [comment]
So seems like all Lua errors associated with the LibDetours has been fixed. Been playing all day, and no errors, even with multiple reloads. However I do get one constant error, but its minor, and doesn't seem to affect anything, but here it is:

420x FontString:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@XIV_Databar_Continued/Classic/modules/travel.lua"]:373: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
