### ISSUE TITLE
[Bug] Siege of Boralus Teleport ID incorrect M+ teleport

### ISSUE THREAD

**Issue by devel1988** [ZelionGG/XIV_Databar-Continued#50]
**Describe the bug**
Siege of Boralus teleport not visable

**To Reproduce**
click on M+ Portals
no Battle For Azeroth menu item

**Expected behavior**
See Battle For Azeroth portals

**WoW Version (please complete the following information)**
 - WoW Flavour: Retail
 - Version 11.0.5

**XIV_Databar Continued Version**
Which version of XIV_Databar Continued are you using ? 3.1

**Additional context**
changed teleportId in the lua files,

                    teleportId = 464256, -- Siege of Boralus Teleport

**Comment by ZelionGG** [comment]
Heya, version 3.2 should fix the teleport ID ! 
Thank you for the feedback and don't hesitate to report any remaining bug !
