### ISSUE TITLE
[Bug] Classic Era Anniversary Realm issue

### ISSUE THREAD

**Issue by deggieq2** [ZelionGG/XIV_Databar-Continued#52]
**Describe the bug**
872x FontString:SetText(): Font not set
Lua Taint: XIV_Databar_Continued
[string "=[C]"]: in function `SetText'
[string "@XIV_Databar_Continued/Classic/modules/Vanilla/travel.lua"]:377: in function `?'
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Attune/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceAttune/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = FontString {
}
(*temporary) = nil

Occurs when auto attacking a mob as a warrior using the current version

**Comment by ZelionGG** [comment]
Heya, thank you for the feedback.

I found code about the portButton that is not a thing in classic so I removed that code and the LUA error shouldn't trigger anymore in the next release of XIV Continued.

**Comment by ZelionGG** [comment]
Heya, release 3.3 should fix your issue, let me know if that's the case and thank you again :D
