### ISSUE TITLE
Lua errors - think it's known but sending. 

### ISSUE THREAD

**Issue by jiberishxd** [ZelionGG/XIV_Databar-Continued#6]
18x .../XIV_Databar_Continued/Mainline/modules/currency.lua:127: attempt to index local 'anchorFrame' (a nil value)
[string "@XIV_Databar_Continued/Mainline/modules/currency.lua"]:127: in function `Refresh'
[string "@XIV_Databar_Continued/Mainline/modules/currency.lua"]:41: in function <.../XIV_Databar_Continued/Mainline/modules/currency.lua:32>

**Comment by ZelionGG** [comment]
Hi, as of version [2.3.2](https://github.com/ZelionGG/XIV_Databar-Continued/releases/tag/v2.3.2), this issue (that was known for a long time now) is finally fixed. Let me know if you encounter issues with that new release.

Thank you again for the feedback.
