### ISSUE TITLE
Hearthstone Button is hard coded to a set ordered list

### ISSUE THREAD

**Issue by RealoFoxtrot** [ZelionGG/XIV_Databar-Continued#8]
There is currently no way to choose which Hearthstone the travel.lua module sets other than editing that file directly.
This has become an issue since hearthstones are now toys instead of items, and there's no way to drop your most preferred Hearthstone into the list.

Suggested fixes:

Quick and Easy fix: 
A setting in the options for the user to select their preferred hearthstone rather than using the list.
Possibly a branch for a random hearthstone to be used?

More detailed fix:
Add a right click context menu similar to the Garrison/Dalaran Hearstone button where a list of all available hearthstones are visible.
After clicking on the selected hearthstone, it is saved as the most recent one to be used when next left clicking on the button

**Comment by ZelionGG** [comment]
Hi, this is an idea I had and, at some point, I will take some time to make that improvement to the Travel module.

Will keep this issue opened just to track that subject, thanks for the suggestion.

**Comment by ZelionGG** [comment]
Heya, release 2.6 added a list of known hearthstones to the Travel module settings, you can check as many as you want and if you check none, the travel module will use its default behavior.

Don't hesitate to check "Use Random Hearthstone" if you check multiple hearthstones 😄 

Enjoy and let me know if you encounter any bug !

**Comment by luimunduk** [comment]
There is a bug with the new version in regards to the added function you have added

2070x XIV_Databar_Continued/Core/modules/system.lua:38: attempt to index field 'system' (a nil value)
[string "@XIV_Databar_Continued/Core/modules/system.lua"]:38: in function `Refresh'
[string "@XIV_Databar_Continued/Core/modules/system.lua"]:25: in function <XIV_Databar_Continued/Core/modules/system.lua:16>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 RegisterFrameEvents = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:209
 Enable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 CreateFrames = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:143
 EnableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 ShowTooltip = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:260
 SecureHook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 baseName = "XIV_Databar_Continued"
 worldPingText = FontString {
 }
 UnregisterAllEvents = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 RawHookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:394
 pingFrame = Button {
 }
 fpsText = FontString {
 }
 fpsIcon = Texture {
 }
 SetOnClickScript = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:187
 SetDefaultModulePrototype = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 fpsFrame = Button {
 }
 systemFrame = Frame {
 }
 elapsed = 0
 name = "XIV_Databar_Continued_SystemModule"
 pingText = FontString {
 }
 IsEnabled = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 GetConfig = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:320
 DisableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetDefaultOptions = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:310
 HookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:365
 HoverFunction = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:154
 UpdateTexts = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:129
 RegisterMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Refresh = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:33
 OnDisable = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:28
 IsHooked = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:492
 OnEnable = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:16
 OnInitialize = <function> defined @XIV_Databar_Continued/Core/modules/system.lua:12
 IsModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 SendMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 UnhookAll = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:476
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 Unhook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:417
 R

**Comment by RealoFoxtrot** [comment]
Can confirm issues. upon loading the addon, get 13 different errors variously claiming that a field (Travel, system, mastervolume, armor, db, etc) are giving a value of nil.

However, one of them throws an error every single frame update:

`Message: ...AddOns/XIV_Databar_Continued/Core/modules/system.lua:38: attempt to index field 'system' (a nil value)
Time: Mon Feb  5 02:15:14 2024
Count: 8259
Stack: ...AddOns/XIV_Databar_Continued/Core/modules/system.lua:38: attempt to index field 'system' (a nil value)
[string "@Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua"]:38: in function `Refresh'
[string "@Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua"]:241: in function <...AddOns/XIV_Databar_Continued/Core/modules/system.lua:235>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 RegisterFrameEvents = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:209
 Enable = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 CreateFrames = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:143
 EnableModule = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 ShowTooltip = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:260
 SecureHook = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 baseName = "XIV_Databar_Continued"
 worldPingText = FontString {
 }
 UnregisterAllEvents = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 RawHookScript = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceHook-3.0/AceHook-3.0.lua:394
 pingFrame = Button {
 }
 fpsText = FontString {
 }
 fpsIcon = Texture {
 }
 SetOnClickScript = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:187
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 fpsFrame = Button {
 }
 systemFrame = Frame {
 }
 elapsed = 183.076004
 name = "XIV_Databar_Continued_SystemModule"
 pingText = FontString {
 }
 IsEnabled = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 GetConfig = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:320
 DisableModule = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 GetDefaultOptions = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:310
 HookScript = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceHook-3.0/AceHook-3.0.lua:365
 HoverFunction = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:154
 UpdateTexts = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:129
 RegisterMessage = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Refresh = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:33
 OnDisable = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:28
 IsHooked = <function> defined @Interface/AddOns/XIV_Databar_Continued/Libs/AceHook-3.0/AceHook-3.0.lua:492
 OnEnable = <function> defined @Interface/AddOns/XIV_Databar_Continued/Core/modules/system.lua:16
 OnInitialize = <function> defined @Interface/AddOns/XIV`

**Comment by ZelionGG** [comment]
Hi guys, thank you for the quick feedbacks, I suggest you to rollback to version 2.4 if you get critical errors.

I'll investigate ASAP on those issues that didn't happen to me.

**Comment by RealoFoxtrot** [comment]
Can confirm it's now functioning

**Comment by ZelionGG** [comment]
> Can confirm it's now functioning

Sweet, thank you for the quick feedback.

Additional information : As of now, the hearthstones list is empty on the first loading, you need to wait a few seconds and do a reload for the list to populate. This is because Blizzard's APIs are making asynchronous call to populate the items cache and I can't refresh the Config after those asynchronous calls.
I'll work on a better solution in the near future.
